[tool.poetry]
name = "worldtalk-webhook"
version = "0.1.0"
description = ""
authors = ["Иван Лисовцов <worldtalk@mail.ru>"]

[tool.poetry.dependencies]
python = "3.10.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
